### ISSUE TITLE
accessExternalDTD not supported

### ISSUE THREAD

**Issue by SztrakaG** [digitalfondue/vatchecker#1]
I have this exception
"java.lang.IllegalArgumentException: Not supported: http://javax.xml.XMLConstants/property/accessExternalDTD"
when my code reach this code:
tf.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, "");

How can i fix it?

**Comment by syjer** [comment]
hi @SztrakaG , which version of java are you using?

edit: ok, I see it may be a dependency issue with xalan. I'll try to reproduce it and fix it on my side :)

**Comment by syjer** [comment]
hi @SztrakaG , could you try with the `1.4.2` version?

**Comment by SztrakaG** [comment]
> hi @SztrakaG , could you try with the `1.4.2` version?

Hello @syjer !

Works perfectly! Thank you!
